spring.application.name=concesionario-autos

spring.datasource.url=jdbc:mysql://192.168.0.141:3306/spring
spring.datasource.username=admin
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
