spring.application.name=concesionario-autos

# Base de datos MySQL (RNF1)
spring.datasource.url=jdbc:mysql://localhost:3306/concesionario?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
